#!/bin/bash

SUCCESS=0
E_DEPLOY_EXISTS=1
E_WRONGPARAMS=2


title()
{
	echo
	echo -e "*** $1 ***"
}

init_hub()
{
	title "Creating HUB repository [$1]";
	mkdir -p $1
	cd $1
	git --bare init
}

init_prime()
{
	#	Creates a new deployment PRIME repository.
	#	Call this after the deploy HUB has been initialised please.

	title "Creating PRIME repository [$2]"
	mkdir -p $2
	cd $2
	git init;
	git remote add  hub $1
	git remote show hub
	git config remote.hub.push HEAD	# Needed by Prime's post-commit hook to push the current branch
}


hub_hook()
{
	# Adds the post-* hooks to HUB and PRIME to keep them in sync.

	HUB_HOOK=$1'/hooks/post-update'
	cat > $HUB_HOOK <<EndOfHubHook
#!/bin/sh

echo
echo "**** Pulling changes into Prime [Hub's post-update hook]"
echo

cd $2 || exit
unset GIT_DIR
git pull hub master

exec git-update-server-info
EndOfHubHook
	chmod u+x $HUB_HOOK
}

prime_hook() 
{
	PRIME_HOOK=$2'/.git/hooks/post-commit'
	cat > $PRIME_HOOK <<EndOfPrimeHook
#!/bin/sh
echo
echo "**** Pushing changes to Hub [Prime's post-commit hook]"
echo
git push hub
EndOfPrimeHook
	chmod u+x $PRIME_HOOK
}


# Test if command line argument present (non−empty).
if [[ "" == "$1" ]]
then
   echo "Please supply the name of the deployment"
   exit $E_WRONGPARAMS
else
   NAME=$1
fi

# Assign default values to ROOTS if needed...
if [[ "" == "$NGD_HUB_ROOT" ]]
then
	NGD_HUB_ROOT=~/.live-hub
fi
if [[ "" == "$NGD_PRIME_ROOT" ]]
then
	NGD_PRIME_ROOT=~/live
fi

NGD_PRIME=$NGD_PRIME_ROOT'/'$NAME'/'
NGD_HUB=$NGD_HUB_ROOT'/'$NAME'.git/'

if cd "$NGD_HUB" 2>/dev/null; then
	echo -e "Directory $NGD_HUB already exists."
	exit $E_DEPLOY_EXISTS
fi

if cd "$NGD_PRIME" 2>/dev/null; then
	echo -e "Directory $NGD_PRIME already exists."
	exit $E_DEPLOY_EXISTS
fi

init_hub   $NGD_HUB
init_prime $NGD_HUB $NGD_PRIME
prime_hook $NGD_HUB $NGD_PRIME

#
#	The --one-way attribute ommits installation of the hub->prime post-update script
#	This allows PRIME -> HUB synchronisations on commits. Essentially making HUB a backup of PRIME.
#	Just arrange for the HUBs to live on a secure remote share and you have some protection against
# failure of your local drive and loss of the work on PRIME.
#
if [[ "--one-way" == "$2" ]]
then
	echo 
	echo "One-way updates requested -- not installing hub post-update hook."
	echo
else
	hub_hook   $NGD_HUB $NGD_PRIME
fi

echo "Done."
